### ISSUE TITLE
Dés de vie

### ISSUE THREAD

**Issue by ombreloup** [HippoAndElephant/Feuille_de_personnage-5E#1]
L'ancien affichage des dés de vie sur trois lignes avait l'énorme avantage de permettre de gérer le multiclassage, et ne prenait pas plus de place que l'actuel sauf erreur. Est il envisageable d'opérer un retour en arrière ?

**Comment by HippoAndElephant** [comment]
La gestion des dés de vie n'a pas été modifiée sur notre fiche. Vous devez confondre avec la fiche Graphic Color de DarkDinDon & Co. 
J'entends cependant votre remarque et une amélioration à ce sujet peut être possible dans une version future.

**Comment by ombreloup** [comment]
Au temps pour moi, je pensais en effet que c'était la graphic color redesigné sans la marque H&D.
Votre travail est aussi bon en tout cas.

**Comment by HippoAndElephant** [comment]
Sur la nouvelle version, j'ai ajouté un dé de vie supplémentaire. En espérant que cela profitera à tes sessions de jeu.

**Comment by ombreloup** [comment]
C'est parfait, merci.
