### ISSUE TITLE
Erreur de calcul perspicacité passive sur le PDF editable

### ISSUE THREAD

**Issue by JDedeWS** [HippoAndElephant/Feuille_de_personnage-5E#2]
Bonjour, 
Je rencontre un problème avec le pdf éditable, le calcule de la perspicacité passible ne se fait pas au bon moment : 
![ex1](https://user-images.githubusercontent.com/22275123/126950367-b464bb26-e825-4ab4-8db1-e9628f68b893.PNG)

Ensuite une fois que je décoche la maitrise, c'est là que la stat passive prend le bonus alors qu'il ne devrait pas
![ex2](https://user-images.githubusercontent.com/22275123/126950373-dbbd153d-b736-4db1-a97f-00a75972e3ca.PNG)

pdf en exemple :
[ex_persp_passive.pdf](https://github.com/HippoAndElephant/Feuille_de_personnage-5E/files/6876416/ex_persp_passive.pdf)

Sinon, super la feuille de perso !!!

**Comment by HippoAndElephant** [comment]
Bien vu ! C'était un petit souci d'ordre de calcul : le calcul ne se faisait qu'après avoir coché une autre case ou ajouté une autre valeur... d'où le train de retard en cochant/décochant. La nouvelle version (2.3.2 - téléchargeable désormais) doit corriger ça. 

Merci du retour !
